# Telegram 配置
telegram:
  token: "8257364097:AAH4fNwUcD9B3ptvMGmKDOVgueyiJHZAHYo"
  channel_id: "@trojan100"
  chat_id: "6445682540"
  parse_mode: "Markdown
  "
  report_time: "21:00" # 每日推送时间（本地时区）
  img_path: "/img"

# yfinance 股票配置
yfinance:
  stocks: # 关注的股票
    - "AAPL"
    - "MSFT"
    - "TSLA"
    - "NVDA"
    - "META"
    - "AMD"
    - "GOOG"
  period: "5d" # 拉取周期
  interval: "1d" # 拉取粒度

# gemini
gemini:
  key: "AIzaSyDAIH59JXJBf5uumwE_roaE7lShXtmcC8s"